N_Asset/N_Asset/urls.py
"""
Definition of urls for N_Asset.
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from app.NA_Views import NA_Goods_View, NA_User_View, NA_Employee_View, NA_LogEvent_View,\
 NA_Suplier_View, NA_EmailData_View, NA_Acc_Fa_View,NA_Goods_Receive_View,NA_Maintenance_View,\
 NA_GoodsLost_View
import app.views
# Uncomment the next lines to enable the admin:
# admin.autodiscover()
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),

    ##User's URL
    url(r'^login/$', NA_User_View.login_view, name='login'),
    url(r'^register/$', NA_User_View.NA_User_Register, name='NA_User_Register'),
    url(r'^profile/(?P<username>\w+)/edit/$', NA_User_View.user_profile, name='user_profile'),
    url(r'^logout/$', NA_User_View.logout_view, name='logout'),

    #NA_Employee
    url(r'^NA_Employee/$', NA_Employee_View.NA_Employee, name='NA_Employee'),
    url(r'^NA_Employee/delete/$', NA_Employee_View.NA_Employee_delete, name='NA_Employee_delete'),
    url(r'^NA_Employee/EntryEmployee/$', NA_Employee_View.EntryEmployee),
    url(r'^NA_Employee/customFilter/$', NA_Employee_View.ShowCustomFilter),
    url(r'^NA_Employee/getData/$', NA_Employee_View.NA_EmployeeGetData, name='NA_Employee_data'),

    #NA_Suplier
    url(r'^NA_Suplier/$', NA_Suplier_View.NA_Suplier, name='NA_Suplier'),
    url(r'^NA_Suplier/delete/$', NA_Suplier_View.NA_Suplier_delete, name='NA_Suplier_delete'),
    url(r'^NA_Suplier/EntrySuplier/$', NA_Suplier_View.EntrySuplier),
    url(r'^NA_Suplier/getData/', NA_Suplier_View.NA_SuplierGetData,name='NA_Suplier_data'),
    url(r'^NA_Suplier/customFilter/$', NA_Suplier_View.ShowCustomFilter),

    #NA_EmailData
    url(r'^NA_EmailData/$', NA_EmailData_View.NA_EmailData, name='NA_EmailData'),
    url(r'^NA_EmailUplData/$', NA_EmailData_View.NA_EmailUplData, name='NA_EmailUplData'),
    url(r'^NA_EmailData/searchBiodata/$', NA_EmailData_View.searchBiodata, name='NA_EmailData_searchBiodata'),
    url(r'^NA_Email/retriveBio/$', NA_EmailData_View.NA_Email_retriveBio, name='NA_Email_retriveBio'),

    ##Log Event
    url(r'^NA_LogEvent/$', NA_LogEvent_View.NA_LogEvent_data, name='NA_LogEvent'),
    url(r'^NA_LogEvent/desc/$', NA_LogEvent_View.LogDescriptions, name='NA_LogEvent_descriptions'),

	#View the Goods
	url(r'^NA_Goods/$',NA_Goods_View.NA_Goods,name='GoodMaster'),
	url(r'^NA_Goods/NA_Goods_Search/$',NA_Goods_View.NA_Goods_Search,name='GoodsManager'),
	url(r'^NA_Goods/SearchBrand/$',NA_Goods_View.Search_Brand, name='SearchBrand'),
    url(r'^NA_Goods/ShowEntry',NA_Goods_View.ShowEntry,name='ShowEntry'),
	url(r'^NA_Goods/customFilter',NA_Goods_View.ShowCustomFilter,name='ShowCustomFilter'),
	url(r'^NA_Goods/Delete/$',NA_Goods_View.deleteItem,name='DeleteGoods'),
	url(r'^NA_Goods/setInActive/$',NA_Goods_View.setInActive,name='SetInActive'),

	#view the goods_receive
	url(r'^NA_Goods_Receive/$',NA_Goods_Receive_View.NA_Goods_Receive,name='GoodsReceive'),
	url(r'^NA_Goods_Receive/NA_Goods_Receive_Search/$',NA_Goods_Receive_View.NA_Goods_Receive_Search,name='GoodsReceiveManager'),
	url(r'^NA_Goods_Receive/ShowEntry_Receive',NA_Goods_Receive_View.ShowEntry_Receive,name='ShowEntryReceivey'),
	url(r'^NA_Goods_Receive/getGoods/$',NA_Goods_Receive_View.getGoods,name='getGoods'),
	url(r'^NA_Goods_Receive/Delete/$',NA_Goods_Receive_View.Delete,name='delete'),
	url(r'^NA_Goods_Receive/HasExists/$',NA_Goods_Receive_View.HasExists,name='HasExists'),
	url(r'^NA_Goods_Receive/getSuplier/$',NA_Goods_Receive_View.getSuplier,name='getSuplier'),
	url(r'^NA_Goods_Receive/getEmployee/$',NA_Goods_Receive_View.getEmployee,name='getEmployee'),
	url(r'^NA_Goods_Receive/SearchGoodsbyForm/$',NA_Goods_Receive_View.SearchGoodsbyForm,name='SearchGoodsbyForm'),
	url(r'^NA_Goods_Receive/SearchSuplierbyForm/$',NA_Goods_Receive_View.SearchSuplierbyForm,name='SearchSuplierbyForm'),
	url(r'^NA_Goods_Receive/SearchEmployeebyform/$',NA_Goods_Receive_View.SearchEmployeebyform,name='SearchEmployeebyform'),
	url(r'^NA_Goods_Receive/getBrandForDetailEntry/$',NA_Goods_Receive_View.getBrandForDetailEntry,name='getBrandForDetailEntry'),
	url(r'^NA_Goods_Receive/getTypeApps/$',NA_Goods_Receive_View.getTypeApps,name='getTypeApps'),
	url(r'^NA_Goods_Receive/getRefNO/$',NA_Goods_Receive_View.getRefNO,name='getRefNO'),
	url(r'^NA_Goods_Receive/deleteDetail/$',NA_Goods_Receive_View.deleteDetail,name='deleteDetail'),
	url(r'^NA_Goods_Receive/customFilter/$',NA_Goods_Receive_View.ShowCustomFilter,name='ShowCustomFilter'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	#NA Acc FA
	url(r'^NA_Acc_FA/$',NA_Acc_Fa_View.NA_Acc_FA, name='NA_Acc'),
	url(r'^NA_Acc_FA/ShowEntry/$',NA_Acc_Fa_View.EntryAcc, name='NA_Acc_Entry'),
    url(r'NA_Acc_FA/getData/$',NA_Acc_Fa_View.NA_AccGetData),
	url(r'^NA_Acc_FA/getGoods/$',NA_Acc_Fa_View.getGoods_data),
    url(r'^NA_Acc_FA/SearchGoodsByForm/$',NA_Acc_Fa_View.SearchGoodsbyForm),
    url(r'^NA_Acc_FA/customFilter/',NA_Acc_Fa_View.ShowCustomFilter),

    #NA Maintenance
    url(r'^NA_Maintenance/$',NA_Maintenance_View.NA_Maintenance,name='NA_Maintenance'),
    url(r'^NA_Maintenance/getData/$',NA_Maintenance_View.NA_MaintenanceGetData),
    url(r'^NA_Maintenance/ShowEntry/$',NA_Maintenance_View.EntryMaintenance),
    url(r'^NA_Maintenance/SearchGoodsByForm/$',NA_Maintenance_View.SearchGoodsbyForm),
    url(r'^NA_Maintenance/getGoods/$',NA_Maintenance_View.get_GoodsData),
    url(r'^NA_Maintenance/delete/$',NA_Maintenance_View.Delete_M_data),

    #NA Goods Lost
    url(r'^NA_GoodsLost/$',NA_GoodsLost_View.NA_Goods_Lost, name='NA_GoodsLost'),
    url(r'^NA_GoodsLost/getData/$',NA_GoodsLost_View.NA_GoodsLost_GetData),
    url(r'^NA_GoodsLost/ShowEntry/$',NA_GoodsLost_View.EntryGoods_Lost),
    url(r'^NA_GoodsLost/SearchGoodsByForm/',NA_GoodsLost_View.SearchGoodsbyForm),
    url(r'^NA_GoodsLost/SearchEmployeeByForm/$',NA_GoodsLost_View.SearchEmployeebyform),
	url(r'^NA_GoodsLost/customFilter/$',NA_GoodsLost_View.ShowCustomFilter),

    #NA Report
    #url(r'^NA_Report/$',NA_Report_View.write_pdf_view),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
]

# untuk akses url media(picture) hasil upload User
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += [
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    ]

N_Asset/NA_Models/models.py
from django.db import models, connections
from datetime import datetime
from NA_DataLayer.NA_Goods_BR import NA_BR_Goods
from django_mysql.models import JSONField
from NA_DataLayer.NA_Goods_BR import NA_BR_Goods,CustomManager
from NA_DataLayer.NA_Goods_Receive_BR import NA_BR_Goods_Receive,CustomSuplierManager,custEmpManager
from NA_DataLayer.NA_Maintenance_BR import NA_BR_Maintenance
from NA_DataLayer.NA_GoodsLost_BR import NA_BR_GoodsLost
from django.core import checks
from django_mysql.utils import connection_is_mariadb
def forced_mariadb_connection(self):
    errors = []

    any_conn_works = False
    conn_names = ['default'] + list(set(connections) - {'default'})
    for db in conn_names:
        conn = connections[db]
        if (
            hasattr(conn, 'mysql_version') and
            connection_is_mariadb(conn) and
            conn.mysql_version >= (5, 7)
        ):
            any_conn_works = True
            #any_conn_works = False

    if not any_conn_works:
        errors.append(
            checks.Error(
                'MySQL 5.7+ is required to use JSONField',
                hint='At least one of your DB connections should be to '
                        'MySQL 5.7+',
                obj=self,
                id='django_mysql.E016'
            )
        )
    return errors

JSONField._check_mysql_version = forced_mariadb_connection
class LogEvent(models.Model):
    idapp = models.AutoField(db_column='IDApp', primary_key=True)
    nameapp = models.CharField(db_column='NameApp', max_length=30)
    descriptions = JSONField()
    createddate = models.DateTimeField(db_column='CreatedDate', auto_now_add=True)
    createdby = models.CharField(db_column='CreatedBy', max_length=30)

    def __str__(self):
        return '{}'.format(self.nameapp)
    def __get_descriptions__(self):
        return self.descriptionsapp
    class Meta:
        db_table = 'LogEvent'

class Employee(models.Model):
    idapp = models.AutoField(db_column='IDApp', primary_key=True)  # Field name made lowercase.
    nik = models.CharField(db_column='NIK', max_length=50)  # Field name made lowercase.
    employee_name = models.CharField(db_column='Employee_Name', max_length=150, blank=True, null=True)  # Field name made lowercase.
    typeapp = models.CharField(db_column='TypeApp', max_length=32, blank=True, null=True)  # Field name made lowercase.
    jobtype = models.CharField(db_column='JobType', max_length=150, blank=True, null=True)  # Field name made lowercase.
    gender = models.CharField(db_column='Gender', max_length=1)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=1)  # Field name made lowercase.
    telphp = models.CharField(db_column='TelpHP', max_length=20, blank=True, null=True)  # Field name made lowercase.
    territory = models.CharField(db_column='Territory', max_length=50, blank=True, null=True)  # Field name made lowercase.
    descriptions = models.CharField(db_column='Descriptions', max_length=50, blank=True, null=True)  # Field name made lowercase.
    inactive = models.IntegerField(db_column='InActive')  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate')  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=100)  # Field name made lowercase.
    modifieddate = models.DateTimeField(db_column='ModifiedDate', blank=True, null=True)  # Field name made lowercase.
    modifiedby = models.CharField(db_column='ModifiedBy', max_length=100, blank=True, null=True)  # Field name made lowercase.

    from NA_DataLayer.NA_Employee import NA_BR_Employee

    objects = NA_BR_Employee()
    customManager = custEmpManager()
    ##objects = models.Manager() #default manager
    class Meta:
        managed = True
        db_table = 'employee'

    def __str__(self):
        return self.employee_name

class NASuplier(models.Model):
    supliercode = models.CharField(db_column='SuplierCode', primary_key=True, max_length=30)  # Field name made lowercase.
    supliername = models.CharField(db_column='SuplierName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=150, blank=True, null=True)  # Field name made lowercase.
    telp = models.CharField(db_column='Telp', max_length=20, blank=True, null=True)  # Field name made lowercase.
    hp = models.CharField(db_column='HP', max_length=20, blank=True, null=True)  # Field name made lowercase.
    contactperson = models.CharField(db_column='ContactPerson', max_length=100, blank=True, null=True)  # Field name made lowercase.
    inactive = models.IntegerField(db_column='InActive')  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=100, blank=True, null=True)  # Field name made lowercase.
    modifieddate = models.DateTimeField(db_column='ModifiedDate', blank=True, null=True)  # Field name made lowercase.
    modifiedby = models.CharField(db_column='ModifiedBy', max_length=100, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return self.supliername

    from NA_DataLayer.NA_Suplier import NA_BR_Suplier

    #NA = NA_BR_Suplier()
    objects = NA_BR_Suplier() #default manager
    customManager = CustomSuplierManager()
    class Meta:
        managed = True
        db_table = 'n_a_suplier'

class NAAccFa(models.Model):
    idapp = models.AutoField(db_column='IDApp', primary_key=True)  # Field name made lowercase.
    fk_goods = models.ForeignKey('goods',db_column='FK_Goods', related_name='AccFA_goods',to_field='idapp')  # Field name made lowercase.
    serialnumber = models.CharField(db_column='SerialNumber',max_length=50)
    typeapp = models.CharField(db_column='TypeApp',max_length=32)
    year = models.DecimalField(db_column='Year', max_digits=10, decimal_places=2)  # Field name made lowercase.
    startdate = models.DateField(db_column='StartDate')  # Field name made lowercase.
    depr_expense = models.DecimalField(db_column='Depr_Expense', max_digits=30, decimal_places=4, blank=True, null=True)  # Field name made lowercase.
    depr_accumulation = models.DecimalField(db_column='Depr_Accumulation', max_digits=30, decimal_places=4, blank=True, null=True)  # Field name made lowercase.
    bookvalue = models.DecimalField(db_column='BookValue', max_digits=30, decimal_places=4, blank=True, null=True)  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate')  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=100, blank=True, null=True)  # Field name made lowercase.
    lastupdated = models.DateTimeField(db_column='LastUpdated', blank=True, null=True)  # Field name made lowercase.

    from NA_DataLayer.NA_Acc_FA import NA_Acc_FA_BR
    objects = NA_Acc_FA_BR()
    class Meta:
        managed = True
        db_table = 'n_a_acc_fa'
    def __str__(self):
        return str(self.fk_goods)

class NAAppparams(models.Model):
    idapp = models.AutoField(db_column='IDApp', primary_key=True)  # Field name made lowercase.
    codeapp = models.CharField(db_column='CodeApp', max_length=64)  # Field name made lowercase.
    nameapp = models.CharField(db_column='NameApp', max_length=100, blank=True, null=True)  # Field name made lowercase.
    typeapp = models.CharField(db_column='TypeApp', max_length=64, blank=True, null=True)  # Field name made lowercase.
    startdate = models.DateField(db_column='StartDate', blank=True, null=True)  # Field name made lowercase.
    enddate = models.DateField(db_column='EndDate', blank=True, null=True)  # Field name made lowercase.
    valuechar = models.CharField(db_column='ValueChar', max_length=50, blank=True, null=True)  # Field name made lowercase.
    fkidapp = models.SmallIntegerField(db_column='FKIDApp', blank=True, null=True)  # Field name made lowercase.
    fkcodeapp = models.CharField(db_column='FKCodeApp', max_length=64, blank=True, null=True)  # Field name made lowercase.
    attstrparams = models.CharField(db_column='AttStrParams', max_length=20, blank=True, null=True)  # Field name made lowercase.
    attdecparams = models.DecimalField(db_column='AttDecParams', max_digits=10, decimal_places=3, blank=True, null=True)  # Field name made lowercase.
    valuestrparams = models.CharField(db_column='ValueStrParams', max_length=50, blank=True, null=True)  # Field name made lowercase.
    valuedecparams = models.DecimalField(db_column='ValueDecParams', max_digits=10, decimal_places=3, blank=True, null=True)  # Field name made lowercase.
    inactive = models.IntegerField(db_column='InActive')  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'n_a_appparams'
        unique_together = (('idapp', 'codeapp'),)


class NADisposal(models.Model):
    idapp = models.AutoField(db_column='IDApp', primary_key=True)  # Field name made lowercase.
    fk_goods = models.CharField(db_column='FK_Goods', max_length=30, blank=True, null=True)  # Field name made lowercase.
    datedisposal = models.DateField(db_column='DateDisposal')  # Field name made lowercase.
    ishasvalue = models.IntegerField(db_column='IsHasValue', blank=True, null=True)  # Field name made lowercase.
    issold = models.IntegerField(db_column='IsSold', blank=True, null=True)  # Field name made lowercase.
    sellingprice = models.DecimalField(db_column='SellingPrice', max_digits=10, decimal_places=4, blank=True, null=True)  # Field name made lowercase.

N_Asset/app/templates/app/MasterData/EntrySuplier.html
<style>
    div.NA-Entry-inlinve-div {
        margin-right:5px
    }
</style>
<form action="EntrySuplier/" method="post" style="width:440px;height:260px;" id="suplier_form" onsubmit="return false">
    {% csrf_token %}
    <style>
        form div.row {
            margin-top:15px
        }
    </style>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_supliercode">Supliercode:</label>
            {{form.supliercode}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_supliername">Supliername:</label>
            {{form.supliername}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_telp">Telp:</label>
            {{form.telp}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_hp">Hp:</label>
            {{form.hp}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_contactperson">Contactperson:</label>
            {{form.contactperson}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_inactive" style="display:inline">Inactive:</label>
            {{form.inactive}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_address">Address:</label>
            {{form.address}}
        </div>
    </div>
    
    {{form.initializeForm}}
    <input type="submit" style="display:none" id="suplier_submit" />
    
</form>

N_Asset/app/templates/app/MasterData/NA_Entry_Employee.html
<form action="EntryEmployee/" method="post" style="width:520px;height:300px;" id="employee_form" onsubmit="return false">
        {% csrf_token %}
    <div class="row" style="margin:0px">
        <div class="col-md-4" style="padding: 0px 10px 0 0;">
            <label for="id_nik" class="left">Nik:</label>
            {{form.nik}}
        </div>
        <div class="col-md-5" style="padding: 0px 10px 0 0;">
            <label class="left" for="id_employee_name">Employee name:</label>
            {{form.employee_name}}
        </div>
        <div class="col-md-3" style="padding: 0 10px 0 0;">
            <label class="left" for="id_typeapp">Typeapp:</label>
            {{form.typeapp}}
        </div>
    </div>

    <div class="row" style="margin:20px 0px 0px 0px">
        <div style="padding:0px 10px 0 0;" class="col-md-4">
            <label for="id_jobtype" class="left">Jobtype:</label>
            {{form.jobtype}}
        </div>
        <div class="col-md-4" style="padding: 0px 5px 0px 5px;">
            <fieldset>
                <legend>
            <div class="col-md-4" style="margin:0 10px 0 0">
                <label for="id_gender_0">Gender:</label>
            </div>
                </legend>
            <ul id="id_gender" style="list-style:none;padding:0px;clear:left;">
                {%for i in form.gender%}
                <li class="col-md-6" style="padding:0px"><label for="{{i.id_for_label}}">{{i.tag}}{{i.choice_label}}</label></li>
                {%endfor%}
            </ul>
            </fieldset>
        </div>
        <div class="col-md-4" style="padding: 0px 5px 0px 5px;">
            <fieldset>
                <legend>
                    <label for="id_status_0" class="left">Status:</label>
                </legend>
                <ul id="id_status" style="list-style:none;clear:left;">
                    {%for i in form.status%}
                    <li class="col-md-6" style="padding:0"><label for="{{i.id_for_label}}">{{i.tag}}{{i.choice_label}}</label></li>
                    {%endfor%}
                </ul>
            </fieldset>
        </div>
    </div>

    <div class="row" style="margin:20px 0 0 0">
        <div class="col-md-4" style="padding: 0px 10px 0px 0px;">
            <label class="left" for="id_telphp">Telphp:</label>
            {{form.telphp}}
        </div>
        <div class="col-md-5" style="padding: 0px">
            <label class="left" for="id_territory">Territory:</label>
            {{form.territory}}
        </div>
        <div class="col-md-2" style="padding:0px;margin: 25px 0 0 25px;">
            <label for="id_inactive" style="margin-left: 7px;">{{form.inactive}}In active</label>
        </div>
    </div>
    <div class="row" style="margin:20px 0 0 0">
        <label for="id_descriptions" class="left">Descriptions:</label>
        {{form.descriptions}}
    </div>
    {{form.initializeForm}}
    <input type="submit" style="display:none" id="employee_submit" />
</form>

N_Asset/app/templates/app/MasterData/NA_Entry_Suplier.html
<style>
    div.NA-Entry-inlinve-div {
        margin-right:5px
    }
</style>
<form action="EntrySuplier/" method="post" style="width:440px;height:260px;" id="suplier_form" onsubmit="return false">
    {% csrf_token %}
    <style>
        form div.row {
            margin-top:15px
        }
    </style>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_supliercode">Supliercode:</label>
            {{form.supliercode}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_supliername">Supliername:</label>
            {{form.supliername}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_telp">Telp:</label>
            {{form.telp}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_hp">Hp:</label>
            {{form.hp}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_contactperson">Contactperson:</label>
            {{form.contactperson}}
        </div>
        <div class="NA-Entry-inlinve-div">
            <label for="id_inactive" style="display:inline">Inactive:</label>
            {{form.inactive}}
        </div>
    </div>
    <div class="NA-Entry-div-row">
        <div class="NA-Entry-inlinve-div">
            <label for="id_address">Address:</label>
            {{form.address}}
        </div>
    </div>
    
    {{form.initializeForm}}
    <input type="submit" style="display:none" id="suplier_submit" />
    
</form>

N_Asset/app/templates/app/MasterData/NA_F_EmailData.html
<form action="." method="post" onsubmit="return false" id="email_data">
    {% csrf_token %}
    <div class="row" style="margin:0px;display:inline-flex;">
        <div class="col-md-5">
            <label for="id_to" class="left">To:</label> 
            <input class="NA-Form-Control" name="to" required="" id="id_to" type="email" placeholder="example@example.com">
        </div>
        <div class="col-md-7">
            <label for="id_subject" class="left">Subject:</label> 
            <input class="NA-Form-Control" name="subject" required="" id="id_subject" type="text" placeholder="Your Subject .. .">
        </div>
        
    </div>
    <div class="row" style="margin:20px 0 0 0;">
    <div style="padding-left: 15px;" class="col-md-5">
        <label for="selectData" class="left">Select Report: </label>
        <select id="selectData" style="display:block;clear:left;width: 182px;">
            <option value="tabular_data">Tabular Data</option>
            <option value="current_data">Current Data</option>
            <option value="biodata">Bio Data</option>
        </select>
    </div>
    <div style="padding: 0;" class="col-md-7">
    <div style="padding: 0;padding-left: 15px;" class="col-md-5">
            <label for="selectTable" class="left">Select Data: </label>
        </div>
        <div style="padding:0px;clear: left;display: inline-block;position: relative;left: 35px;padding-right: 8px;" class="col-md-11">
            <div class="checkbox checkbox-success" style="padding:0px;text-align: left;margin-top:0px;display: inline-block;float: left;">
                <input id="employee_email" value="employee_emailData" type="checkbox"><label for="employee_email">Employee</label>
            </div>
            <div class="checkbox checkbox-success" style="padding:0px;text-align: left;margin-top:0px;display: inline-block;float: left;margin-left: 30px;">
                <input id="suplier_email" value="suplier_emailData" type="checkbox"><label for="suplier_email">Suplier</label>
            </div>
            <div class="checkbox checkbox-success" style="padding:0px;text-align:left;margin-top:0px;display: inline-block;float: left;margin-left: 30px;">
                <input id="goods_email" value="goods_emailData" type="checkbox"><label for="goods_email">Goods</label>
            </div>
        </div>
    </div>
</div>
    <div class="row" style="margin:12px 0 0 0" id="searchBioContainer">
        <div class="col-md-6" style="padding-right:0">
            <label for="searchBiodata" class="left">Search Data: </label>
            <input class="NA-Form-Control" id="searchBiodata" disabled="disabled" type="text" placeholder="Search biodata .. ." style="width:77%">
        </div>
        <div class="col-md-6" id="resultSearch">

        </div>
    </div>
    <div class="row" style="margin:12px 0 0 0">
        <div class="col-md-12">
            <label for="id_message" class="left">Message:</label>
            <textarea class="NA-Form-Control" name="message" required="" id="id_message" maxlength="250" style="max-width: 500px; width: 462px; height: 52px; clear: left;" placeholder="Enter your message .. ."></textarea>
        </div>
    </div>
    <input type="hidden" id="initializeEmail" />
    <input type="submit" style="display:none" id="emailData_submit"/>
</form>