N_Asset/N_Asset/urls.py
"""
Definition of urls for N_Asset.
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from app.NA_Views import NA_Goods_View, NA_User_View, NA_Employee_View, NA_LogEvent_View,\
 NA_Suplier_View, NA_EmailData_View, NA_Acc_Fa_View,NA_Goods_Receive_View,NA_Maintenance_View,\
 NA_GoodsLost_View
import app.views
# Uncomment the next lines to enable the admin:
# admin.autodiscover()
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),

    ##User's URL
    url(r'^login/$', NA_User_View.login_view, name='login'),
    url(r'^register/$', NA_User_View.NA_User_Register, name='NA_User_Register'),
    url(r'^profile/(?P<username>\w+)/edit/$', NA_User_View.user_profile, name='user_profile'),
    url(r'^logout/$', NA_User_View.logout_view, name='logout'),

    #NA_Employee
    url(r'^NA_Employee/$', NA_Employee_View.NA_Employee, name='NA_Employee'),
    url(r'^NA_Employee/delete/$', NA_Employee_View.NA_Employee_delete, name='NA_Employee_delete'),
    url(r'^NA_Employee/EntryEmployee/$', NA_Employee_View.EntryEmployee),
    url(r'^NA_Employee/customFilter/$', NA_Employee_View.ShowCustomFilter),
    url(r'^NA_Employee/getData/$', NA_Employee_View.NA_EmployeeGetData, name='NA_Employee_data'),

    #NA_Suplier
    url(r'^NA_Suplier/$', NA_Suplier_View.NA_Suplier, name='NA_Suplier'),
    url(r'^NA_Suplier/delete/$', NA_Suplier_View.NA_Suplier_delete, name='NA_Suplier_delete'),
    url(r'^NA_Suplier/EntrySuplier/$', NA_Suplier_View.EntrySuplier),
    url(r'^NA_Suplier/getData/', NA_Suplier_View.NA_SuplierGetData,name='NA_Suplier_data'),
    url(r'^NA_Suplier/customFilter/$', NA_Suplier_View.ShowCustomFilter),

    #NA_EmailData
    url(r'^NA_EmailData/$', NA_EmailData_View.NA_EmailData, name='NA_EmailData'),
    url(r'^NA_EmailUplData/$', NA_EmailData_View.NA_EmailUplData, name='NA_EmailUplData'),
    url(r'^NA_EmailData/searchBiodata/$', NA_EmailData_View.searchBiodata, name='NA_EmailData_searchBiodata'),
    url(r'^NA_Email/retriveBio/$', NA_EmailData_View.NA_Email_retriveBio, name='NA_Email_retriveBio'),

    ##Log Event
    url(r'^NA_LogEvent/$', NA_LogEvent_View.NA_LogEvent_data, name='NA_LogEvent'),
    url(r'^NA_LogEvent/desc/$', NA_LogEvent_View.LogDescriptions, name='NA_LogEvent_descriptions'),

	#View the Goods
	url(r'^NA_Goods/$',NA_Goods_View.NA_Goods,name='GoodMaster'),
	url(r'^NA_Goods/NA_Goods_Search/$',NA_Goods_View.NA_Goods_Search,name='GoodsManager'),
	url(r'^NA_Goods/SearchBrand/$',NA_Goods_View.Search_Brand, name='SearchBrand'),
    url(r'^NA_Goods/ShowEntry',NA_Goods_View.ShowEntry,name='ShowEntry'),
	url(r'^NA_Goods/customFilter',NA_Goods_View.ShowCustomFilter,name='ShowCustomFilter'),
	url(r'^NA_Goods/Delete/$',NA_Goods_View.deleteItem,name='DeleteGoods'),
	url(r'^NA_Goods/setInActive/$',NA_Goods_View.setInActive,name='SetInActive'),

	#view the goods_receive
	url(r'^NA_Goods_Receive/$',NA_Goods_Receive_View.NA_Goods_Receive,name='GoodsReceive'),
	url(r'^NA_Goods_Receive/NA_Goods_Receive_Search/$',NA_Goods_Receive_View.NA_Goods_Receive_Search,name='GoodsReceiveManager'),
	url(r'^NA_Goods_Receive/ShowEntry_Receive',NA_Goods_Receive_View.ShowEntry_Receive,name='ShowEntryReceivey'),
	url(r'^NA_Goods_Receive/getGoods/$',NA_Goods_Receive_View.getGoods,name='getGoods'),
	url(r'^NA_Goods_Receive/Delete/$',NA_Goods_Receive_View.Delete,name='delete'),
	url(r'^NA_Goods_Receive/HasExists/$',NA_Goods_Receive_View.HasExists,name='HasExists'),
	url(r'^NA_Goods_Receive/getSuplier/$',NA_Goods_Receive_View.getSuplier,name='getSuplier'),
	url(r'^NA_Goods_Receive/getEmployee/$',NA_Goods_Receive_View.getEmployee,name='getEmployee'),
	url(r'^NA_Goods_Receive/SearchGoodsbyForm/$',NA_Goods_Receive_View.SearchGoodsbyForm,name='SearchGoodsbyForm'),
	url(r'^NA_Goods_Receive/SearchSuplierbyForm/$',NA_Goods_Receive_View.SearchSuplierbyForm,name='SearchSuplierbyForm'),
	url(r'^NA_Goods_Receive/SearchEmployeebyform/$',NA_Goods_Receive_View.SearchEmployeebyform,name='SearchEmployeebyform'),
	url(r'^NA_Goods_Receive/getBrandForDetailEntry/$',NA_Goods_Receive_View.getBrandForDetailEntry,name='getBrandForDetailEntry'),
	url(r'^NA_Goods_Receive/getTypeApps/$',NA_Goods_Receive_View.getTypeApps,name='getTypeApps'),
	url(r'^NA_Goods_Receive/getRefNO/$',NA_Goods_Receive_View.getRefNO,name='getRefNO'),
	url(r'^NA_Goods_Receive/deleteDetail/$',NA_Goods_Receive_View.deleteDetail,name='deleteDetail'),
	url(r'^NA_Goods_Receive/customFilter/$',NA_Goods_Receive_View.ShowCustomFilter,name='ShowCustomFilter'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	#NA Acc FA
	url(r'^NA_Acc_FA/$',NA_Acc_Fa_View.NA_Acc_FA, name='NA_Acc'),
	url(r'^NA_Acc_FA/ShowEntry/$',NA_Acc_Fa_View.EntryAcc, name='NA_Acc_Entry'),
    url(r'NA_Acc_FA/getData/$',NA_Acc_Fa_View.NA_AccGetData),
	url(r'^NA_Acc_FA/getGoods/$',NA_Acc_Fa_View.getGoods_data),
    url(r'^NA_Acc_FA/SearchGoodsByForm/$',NA_Acc_Fa_View.SearchGoodsbyForm),
    url(r'^NA_Acc_FA/customFilter/',NA_Acc_Fa_View.ShowCustomFilter),

    #NA Maintenance
    url(r'^NA_Maintenance/$',NA_Maintenance_View.NA_Maintenance,name='NA_Maintenance'),
    url(r'^NA_Maintenance/getData/$',NA_Maintenance_View.NA_MaintenanceGetData),
    url(r'^NA_Maintenance/ShowEntry/$',NA_Maintenance_View.EntryMaintenance),
    url(r'^NA_Maintenance/SearchGoodsByForm/$',NA_Maintenance_View.SearchGoodsbyForm),
    url(r'^NA_Maintenance/getGoods/$',NA_Maintenance_View.get_GoodsData),
    url(r'^NA_Maintenance/delete/$',NA_Maintenance_View.Delete_M_data),

    #NA Goods Lost
    url(r'^NA_GoodsLost/$',NA_GoodsLost_View.NA_Goods_Lost, name='NA_GoodsLost'),
    url(r'^NA_GoodsLost/getData/$',NA_GoodsLost_View.NA_GoodsLost_GetData),
    url(r'^NA_GoodsLost/ShowEntry/$',NA_GoodsLost_View.EntryGoods_Lost),
    url(r'^NA_GoodsLost/SearchGoodsByForm/',NA_GoodsLost_View.SearchGoodsbyForm),
    url(r'^NA_GoodsLost/SearchEmployeeByForm/$',NA_GoodsLost_View.SearchEmployeebyform),
	url(r'^NA_GoodsLost/customFilter/$',NA_GoodsLost_View.ShowCustomFilter),

    #NA Report
    #url(r'^NA_Report/$',NA_Report_View.write_pdf_view),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
]

# untuk akses url media(picture) hasil upload User
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += [
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    ]

N_Asset/NA_DataLayer/NA_User/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse

USERNAME_REGEX = '^[a-zA-Z0-9.+-]*$'
NAME_REGEX = '^[a-zA-Z]*$'


class User(AbstractUser):
    username = models.CharField(max_length=250,unique=True, blank=False,
                                validators=[
                                        RegexValidator(
                                        regex = USERNAME_REGEX,
                                        message = 'Username must be Alpahnumeric or contain any of the following: ".+ -" ',
                                        code='invalid_username'
                                        )]
                                )
    first_name = models.CharField(max_length=256, blank=False,
                                  validators=[
                                        RegexValidator(
                                        regex = NAME_REGEX,
                                        message = 'Name must be Alphabetic',
                                        code='invalid_first_name'
                                        )]
                                )
    last_name = models.CharField(max_length=256, blank=False,
                                  validators=[
                                        RegexValidator(
                                        regex = NAME_REGEX,
                                        message = 'Name must be Alphabetic',
                                        code='invalid_last_name'
                                        )]
                                )
    email = models.EmailField(unique=True, blank=True)
    picture = models.ImageField(null=True, 
                                blank=True, 
                                default='default.png',
                                height_field="height_field", 
                                width_field="width_field",
                                verbose_name="profile picture"
                                )
    height_field = models.IntegerField(default=600, null=True)
    width_field = models.IntegerField(default=600, null=True)
    USERNAME_FIELD = 'email' # use email to log in
    REQUIRED_FIELDS = ['username'] # required when user is created

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("user_profile", kwargs={"username": self.username})

N_Asset/NA_DataLayer/NA_User/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.forms.extras.widgets import SelectDateWidget
from .models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("User Does Not Exist.")
            if not user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not user.is_active:
                raise forms.ValidationError("User is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name",
                  "last_name", 
                  "username", 
                  "email", 
                  "picture", 
                  "password1", 
                  "password2" )

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user


class UserProfileUpdateForm(forms.ModelForm, forms.Form):
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User 
        fields = ("first_name", 
                  "last_name", 
                  "email", 
                  "picture")

N_Asset/app/templates/app/NA_User/NA_User_Profile.html
            <form class="form-horizontal" role="form" method="post" action="{% url 'user_profile' user.username %}" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="textinput">First name</label>
                    <div class="col-sm-8">
                        <input class="form-control white" name="first_name" id="id_first_name" maxlength="256" value="{{ request.user.first_name }}" required="" type="text" placeholder="First Name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="textinput">Last name</label>
                    <div class="col-sm-8">
                        <input class="form-control white" name="last_name" id="id_last_name" maxlength="256" value="{{ request.user.last_name }}" required="" type="text" placeholder="Last Name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="textinput">Email</label>
                    <div class="col-sm-8">
                        <input class="form-control white" name="email" id="id_email" maxlength="254" value="{{ request.user.email }}" autofocus="" type="email" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="textinput">Picture</label>
                    <div class="col-sm-4">
                    <input name="picture" id="id_picture" type="file">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="textinput">Confirm Password</label>
                    <div class="col-sm-8">
                        <input class="form-control white" name="confirm_password" id="id_confirm_password" type="password" placeholder="Password">
                    </div>
                </div>
              <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn gradient-green">Save</button>
			  </div>
            </form>

N_Asset/app/templates/app/NA_User/NA_User_Register.html
<style>
.form-group{
	margin-bottom: 15px;
}

label{
	margin-bottom: 15px;
}

input,
input::-webkit-input-placeholder {
    font-size: 11px;
    padding-top: 3px;
}


.main-center{
 	margin-top: 30px;
 	margin: 0 auto;
 	max-width: 330px;
    background:none
}

.login-button{
	margin-top: 5px;
}

.login-register{
	font-size: 11px;
	text-align: center;
}
#form_user {
    background:none;
    width:450px;
    margin:10px 0 30px 0;
}
.left-label{
    text-align:left;
    font-weight:bold
}
span.input-group-addon {
    background:white;
    border-color:#4CAF50;
    color:#4CAF50;
}
form#form_user input.form-control {
    border-left-color:#4CAF50;
    box-shadow:none
}
form#form_user input.form-control:focus {
    border-color:#4CAF50;
    box-shadow:none
}
</style>
<form class="form-horizontal" method="post" action="{% url 'register' %}" id="form_user" enctype="multipart/form-data">
    {% csrf_token %}
	<div class="row">
		<div class="col-sm-6">
            <label for="name" class="control-label" style="text-align: left;font-weight:bold">First Name :</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
				{{form.first_name}}
			</div>
		</div>
        <div class="col-sm-6" style="padding: 0 15px 0 0;">
            <label for="name" class="control-label" style="text-align: left;font-weight:bold">Last Name :</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
				{{form.last_name}}
			</div>
		</div>
	</div>
    <div class="row">
		<div class="col-sm-6">
            <label for="username" class="control-label" style="text-align: left;font-weight:bold">Username :</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
				{{form.username}}
			</div>
		</div>
        <div class="col-sm-6">
            <label class="control-label" for="textinput" style="text-align: left;font-weight:bold">Picture :</label>
            {{form.picture}}
        </div>
	</div>
	<div class="row">
		<div class="col-sm-12">
            <label for="email" class="control-label" style="text-align: left;font-weight:bold">Email :</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
				{{form.email}}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
            <label for="password" class="control-label" style="text-align: left;font-weight:bold">Password :</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
				{{form.password1}}
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-sm-12">
            <label for="confirm" class="control-label" style="text-align: left;font-weight:bold">Confirm Password :</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
				{{form.password2}}
			</div>
		</div>
    </div>
    <input type="submit" style="display:none" id="user_submit"/>
    {{form.initializeForm_user}}
</form>